### ISSUE TITLE
call to colorize needs ** in ruby 3.0.0

### ISSUE THREAD

**Issue by graial** [vifreefly/rbcat#1]
As per:
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

there are broken method calls when trying to use this gem in ruby 3.0.0.

the colorize call in 

> gems/rbcat-0.2.1/lib/rbcat.rb

 fails in ruby 3.0.0 until you add a ** to options ie
    `Colorizer.colorize(string, **options)`

and public_send in:
> gems/kimurai-1.4.0/lib/kimurai/base.rb

should be:
`public_send( handler, browser.current_response(response_type), **{ url: url, data: data })`

**Comment by deanopound** [comment]
Hey @graial, I've addressed the issue in https://github.com/vifreefly/rbcat/pull/3

**Comment by vifreefly** [comment]
Fixed with 0.2.2 (https://github.com/vifreefly/rbcat/blob/master/CHANGELOG.md#022)
